# Generated by Django 3.1.7 on 2021-11-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0002_auto_20211120_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
