# Generated by Django 3.1.7 on 2021-12-07 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0003_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Введите текст'),
        ),
    ]
