# Generated by Django 3.0.3 on 2021-12-09 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0004_auto_20211208_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=''),
        ),
    ]
