# Generated by Django 3.0.3 on 2021-12-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0007_auto_20211209_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
