# Generated by Django 3.0.3 on 2021-12-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0008_auto_20211209_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
