# Generated by Django 3.1.7 on 2021-12-15 00:03

import app_ct.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0010_auto_20211214_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=app_ct.models.CustomDateTimeField(editable=False),
        ),
    ]
