# Generated by Django 3.0.3 on 2022-01-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0013_auto_20220109_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
    ]
