# Generated by Django 3.1.7 on 2022-01-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ct', '0015_bookmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
