# Generated by Django 3.0.3 on 2022-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220109_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='yavtanke72@yandex.ru', max_length=254),
            preserve_default=False,
        ),
    ]
