# Generated by Django 3.0.3 on 2022-01-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
