# Generated by Django 3.1.7 on 2022-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=1000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='', max_length=15, verbose_name='Мобильный номер'),
        ),
    ]
