# Generated by Django 3.0.3 on 2022-01-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_historicalprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
    ]
