# Generated by Django 3.1.7 on 2022-01-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220117_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkuser',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Подписки на пользователей'},
        ),
    ]
