# Generated by Django 3.1.7 on 2022-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220120_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Cooбщение'),
        ),
    ]
