# Generated by Django 3.1.7 on 2022-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220120_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
