# Generated by Django 3.1.7 on 2022-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.png', null=True, upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
