# Generated by Django 3.1.7 on 2022-02-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220206_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.png', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
