# Generated by Django 3.1.7 on 2022-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
