# Generated by Django 3.1.7 on 2021-12-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bookmarkpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkpost',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
    ]
