# Generated by Django 3.0.3 on 2021-12-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211205_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(verbose_name='Просмотры'),
        ),
    ]
