# Generated by Django 3.0.3 on 2022-01-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bookmarkpost_created_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='created_dt',
            new_name='created_bk',
        ),
    ]
