# Generated by Django 3.0.3 on 2022-01-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220109_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='created_bk',
            new_name='created',
        ),
    ]
