# Generated by Django 3.0.3 on 2022-01-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220109_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='created',
            new_name='created_at',
        ),
    ]
