# Generated by Django 3.0.3 on 2022-01-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220109_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='created_at',
            new_name='created',
        ),
    ]
