# Generated by Django 3.0.3 on 2022-01-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220110_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='created',
            new_name='created_at',
        ),
    ]
